### ISSUE TITLE
`--self-extracting` option

### ISSUE THREAD

**Issue by tomodachi94** [walksanatora/imgtool-rs#1]
Putting this here so it doesn't get lost inside of the MCCM Discord.

This feature would add a `--self-extracting` flag, which would use SEA to generate a self-extracting archive.

**Comment by walksanatora** [comment]
currently working on the `-c --compressed` option for gzipping output
then i will get --self-extracting working (currently wondering how to get a Vec<u8> from lua instead of a UTF8 string)

**Comment by walksanatora** [comment]
(note currently it is uhhh *cursed* in that GZ/UNGZ are apart of the FS library, (and they are all methods so you use : instead of .))

**Comment by walksanatora** [comment]
@tomodachi94 i finally got enough focus and got it fixed and working (and with Gzip also)
